# Test actions
#---------- Copyright by DmitriyM

name: testaction
env:
  deploy_version: "deploy_version_${{ github.sha }}"
on:
  push:
    branches:
      - main
jobs:
  printdir:
    runs-on: ubuntu-latest
    env:
      var1: " var in jobs 1 "
      var2: " var in jobs 2 "
    steps:
      - uses: actions/checkout@v2
      - name: echodir
        run: ls -las
      - name: echovars
        run: |
          echo "var1 is ${{ env.var1 }}"
          echo "var2 is ${{ env.var2 }}"
          echo "var3 is $localvar"
       env:
         localvar: "this local var"

  checkver: 

    runs-on: ubuntu-latest
    needs: [printdir]
    
    steps: 
      - name: echo deploy ver
        run: echo "deploy_version is ${{ env.deploy_version }}"
      
